### ISSUE TITLE
拖动进度条后，不会自动播放

### ISSUE THREAD

**Issue by hussion** [peacefulprogram/ddys#1]
拖动进度条后，视频会暂停，不会自动播放，需要手动进行恢复播放

**Comment by peacefulprogram** [comment]
这两天网站换了接口，还加了一些加密参数的校验

**Comment by hussion** [comment]
> 这两天网站换了接口，还加了一些加密参数的校验

我说的这个问题，感觉应该是seekTo之后，没有执行play方法

**Comment by peacefulprogram** [comment]
> > 这两天网站换了接口，还加了一些加密参数的校验
> 
> 
> 
> 我说的这个问题，感觉应该是seekTo之后，没有执行play方法

快进后按OK会开始播放，这块是leanback封装的，我前两天使用的时候也发现seek之后不会播放，然后发现网站上换了接口，用新接口查到的视频链接可以正常快进，然后昨天那个接口又加了校验，等后面一起处理吧。现在可以先用[555dy-tv](https://github.com/peacefulprogram/555dy-tv)
