### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by siyige2727** [peacefulprogram/ddys#2]
你好，想请教一下，apk安装失败是跟我电视系统不兼容嘛

**Comment by peacefulprogram** [comment]
最低支持到Android 5,你看看系统版本

**Comment by siyige2727** [comment]
看了一下是安卓10，感觉就是最近电视系统更新了一下就用不了了，之前是可以安装的，是真的好用，现在离了电视都不想开了。。

**Comment by peacefulprogram** [comment]
前面发布的版本能安装吗?按理说10应该没问题啊,我的电视是9

**Comment by siyige2727** [comment]
1.0在我电视系统更新之前是可以安装的，也挺好用的，估计还是我的电视系统更新了什么乱七八遭的东西

**Comment by peacefulprogram** [comment]
那我帮不了你了,1.1就只是加了一个网站的cookie校验,你看看电视里的安全相关的设置吧

**Comment by siyige2727** [comment]
好的，谢谢了，我估计也是我自己电视的问题，感谢感谢，真的很好用
