### ISSUE TITLE
[FR] Proxy supports

### ISSUE THREAD

**Issue by AlexV525** [peacefulprogram/ddys#3]
Thanks for the great project!

Since corresponding domains are usually slow or blocked, it would be better to support an explicit setting to use a proxy by specifying *host* and *port* only, which allows users to redirect requests to a LAN (or WAN) proxy.

> 域名时常慢或被阻止，可否提供一个代理 **地址** 和 **端口** 设置，让用户可以使用局域网或其他指定地址的代理？

**Comment by peacefulprogram** [comment]
I'll add this feature when I have time.

**Comment by peacefulprogram** [comment]
[添加代理设置](https://github.com/androidx/media/commit/ba4b96d2c1acb15830dd75cef8173eab12282444)
