### ISSUE TITLE
[BUG] Unable to play after long idle times

### ISSUE THREAD

**Issue by AlexV525** [peacefulprogram/ddys#7]
If the app is idle for about 30 minutes (maybe less or more), media cannot be played anymore.

This might not be an app-specific issue, I saw the website ran into this occasionally.

![image](https://github.com/peacefulprogram/ddys/assets/15884415/52bec9cc-1fdc-4729-b240-99c1ff002c83)

**Comment by peacefulprogram** [comment]
can't be solved from app
