### ISSUE TITLE
[BUG] 加载详情失败:null

### ISSUE THREAD

**Issue by AlexV525** [peacefulprogram/ddys#9]
Version: v1.2.4

外籍之人 https://ddys.pro/expats/ 在应用中无法加载详情

![Screenshot_2024-02-07-00-57-11-39_8c94a5ef81e3eb466797d476ef5790e0](https://github.com/peacefulprogram/ddys/assets/15884415/4e11dc32-24b7-4f3f-adb1-809b8a3e1a8b)

**Comment by peacefulprogram** [comment]
视频详情是一张图片导致的, 已修复
